# Generated by Django 4.1 on 2022-09-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_ceo', models.CharField(max_length=200)),
                ('company_address', models.TextField(max_length=400)),
                ('company_inception', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('team_lead_name', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.company')),
            ],
        ),
    ]
